apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: buildah-taskrun
spec:
  taskRef:
    name: buildah-task
  inputs:
    resources:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/Divyansh42/simple-golang-webserver
  outputs:
    resources:
      - name: image
        resourceSpec:
          type: image
          params:
            - name: url
              value: image-registry.openshift-image-registry.svc:5000/simple-golang-app/simple-golang-webserver:latest