apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-golang-app
  labels:
    app: simple-golang-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-golang-app
  template:
    metadata:
      labels:
        app: simple-golang-app
    spec:
      containers:
        - name: simple-golang-webserver
          image: quay.io/diagrawa/simple-golang-webserver:v1
          ports:
            - containerPort: 4000