apiVersion: v1
kind: Service
metadata:
  name: simple-golang-app-service
spec:
  type: NodePort
  selector:
    app: simple-golang-app
  ports:
    - protocol: TCP
      port: 40
      targetPort: 4000